// Importing createSlice from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Creating a slice for authentication
const authSlice = createSlice({
    
    // Name of the slice
    name: "auth",
    initialState: { isLoggedIn: false, role: "user" },  // Initial state of the slice
    reducers: {
        // Reducer to handle login action
        login(state) {
            state.isLoggedIn = true;    // Update the state to indicate the user is logged in
        },
        // Reducer to handle logout action
        logout(state) {
            state.isLoggedIn = false;   // Update the state to indicate the user is logged out
        },
        // Reducer to handle role change action
        changeRole(state, action) {
            const role = action.payload;    // Extracting the new role from the action payload
            state.role = role;  // Update the state with the new role
        },
    },
});

export const authActions = authSlice.actions;   // Exporting the actions generated by createSlice
export default authSlice.reducer;   // Exporting the reducer to be included in the store